services:
  - type: web
    name: bloodbankmanagement
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn bloodbankmanagement.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DISABLE_COLLECTSTATIC
        value: 0
    healthCheckPath: /

databases:
  - name: bloodbankdb
    plan: free
    databaseName: bloodbank
    user: bloodbank_user
